### ISSUE TITLE
Edit Notice

### ISSUE THREAD

**Issue by ttakkku** [rookieman88/DiscordJs-NoticeBot#1]
I'd like to send it to a certain room.

**Comment by rookieman88** [comment]
https://github.com/rookieman88/WaterBotv2/blob/6544fce2091ebc26716f319e7dbe2994dbc9ae63/commands/%EC%A0%84%EC%B2%B4%EA%B3%B5%EC%A7%80.js
랑
https://github.com/rookieman88/WaterBotv2/blob/6544fce2091ebc26716f319e7dbe2994dbc9ae63/commands/%EC%B1%84%EB%84%90%EC%84%A4%EC%A0%95.js
를  참고하시면 됩니다
